---
/**:
  ros__parameters:
    cameras: [frontleft, frontright]
    state_poll_period_s: 0.01
    robot:
      setup_logging: false
      should_retry: true
      ip: 192.168.80.3
      username: $(env ADT4_BOSDYN_USERNAME)
      password: $(env ADT4_BOSDYN_PASSWORD)
